<?php

/**
 * Implementation of hook_menu().
 */
function blankstyle_developer_test_menu() {

  $items['product/s2'] = array(
    'title' => 'Call API',
    'page callback' => 'blankstyle_developer_test_page_show_info',
    'access callback' => TRUE,
  );

  return $items;
}

/**
 *
 * @param string $url
 * @param string|array $post_fields
 * @param array $headers
 * @return type
 */
function cUrlGetData($url, $post_fields = null, $headers = null){
    if(!function_exists('curl_init')) {
        die('cURL not available!');
    }
    $ch = curl_init();
    $timeout = 5;
    curl_setopt($ch, CURLOPT_URL, $url);
    if (!empty($post_fields)) {
        $data_string = json_encode($post_fields);
        curl_setopt($ch, CURLOPT_POST, 1);
        curl_setopt($ch, CURLOPT_POSTFIELDS, $data_string);
    }
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    if (!empty($headers))
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 1);
    curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 1);
    curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, $timeout);
    $data = curl_exec($ch);
    if (curl_errno($ch)) {
        echo 'Error:' . curl_error($ch);
    }
    curl_close($ch);
    return $data;
}

/**
 * A simple page callback.
 * */
function blankstyle_developer_test_page_show_info() {
    drupal_add_css(drupal_get_path('module', 'blankstyle_developer_test') .'/css/variants.css');
    drupal_add_js(drupal_get_path('module', 'blankstyle_developer_test') . '/js/variants.js');

    $url = "http://blankstyle-backend-api-dev.us-west-2.elasticbeanstalk.com/product/query";
    $post_fields = array(
        "limit" => 1,
        "filters" => array(
            "sku.AP" => "3600"
        )
    );
    $headers = [
        'x-api-key: 3f3a08b75714fafaacbef538a4ef72474d7f8189f8943d3b151f38327c274388',
        'Accept: application/json',
        'Content-Type: application/json'];
    $data = cUrlGetData($url, $post_fields, $headers);
    $products = json_decode($data);
    $output = '';
    if(!empty($products)) {


        foreach ($products as &$product) {
            $output .= '<div class="dropdown">';
            $output .= '<label for="variants">Select Variant</label>';
            $output .= ' <select name="variants" id="variants">';
            foreach($product->name as $key => $variant){

                $selected = $key == 'S2' ? 'selected="selected"' : '';

                $output .= '   <option '.$selected.'  value="'.$key.'">  '.$key.' - '.$variant.'</option>';
            }
            $output .= '</select></div>';

            drupal_set_title(check_plain($product->name->S2));
            $output .= '<div id="products-list">';
            foreach($product->name as $key => $variant){
                $output .= '<div id="'.$key.'" class="product-item">';

                $output .= '<p><img src="'.check_url($product->images->$key->front).'" style="width: 320px;float: left;margin-right: 20px;" /></p>';
                $output .= '<p>'.t($product->description->$key).'</p>';
                $output .= '</div>';
            }
            $output .= '</div>';





        }
    }
  return $output;
}
